### ISSUE TITLE
Incorrect sorting on non-Chrome browsers.

### ISSUE THREAD

**Issue by Adelscott** [EskiMojo14/keycaplendar#1] opened 2020-04-19 21:13 UTC
Sorting is weird, it is neither ascending nor descending : 

July 2020 (2)
January 2021 (1)
May 2020 (9)
April 2020 (16)
June 2020 (7)
October 2020 (2)
August 2020 (1)
March 2020 (1)

I don't get how it's sorted !

**Comment by EskiMojo14** [comment] 2020-04-19 21:27
Hi! Thanks for the report.

I'm struggling to replicate this issue, using Chrome. Which browser are you using?

Could you also check the console to see if any errors are returned?

Thanks

**Comment by Adelscott** [comment] 2020-04-19 22:12
I'm using Firefox 75
Same issue on Edge
On Chrome it's OK, it's sorted ascending

I don't see any error in console

**Comment by Adelscott** [comment] 2020-04-19 22:17
In fact there's a  warning : 
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?l=dataLayer”.

**Comment by EskiMojo14** [comment] 2020-04-19 22:37
Can confirm that issue occurs on Firefox and Edge. Not entirely sure why.

Warning mentioned appears to be unrelated - possibly due to a tracker blocker.

**Comment by EskiMojo14** [comment] 2020-05-01 14:02
Discovered cause of issue - date parsing in Chrome is inconsistent with other browsers.

Other browsers require dates in ISO 8601 format, i.e. yyyy-mm-dd. Chrome also accepts other values such as "March 2020", which is why the previous method of sorting worked on Chrome but no others.

Fixed in commit [d09db4108379fdf2b766f287ab430b5ce15ed3dd](https://github.com/EskiMojo14/keycaplendar/commit/d09db4108379fdf2b766f287ab430b5ce15ed3dd).

**Comment by EskiMojo14** [comment] 2020-05-19 09:10
Re-opening - sorting is still incorrect in Safari, as it does not accept ISO 8601 dates.

I suspect I shall have to use Moment.js, or possibly sort alphabetically (as ISO 8601 dates should theoretically sort alphabetically).

**Comment by EskiMojo14** [comment] 2020-06-03 16:03
Converting group names to ISO 8601 and sorting alphabetically works, and I have confirmed this resolves the issue found in Safari.

**Closed by EskiMojo14** 2020-06-03 16:03 UTC
Labels: bug
